---
name: DevOps Pipeline

on: 
  push:
    branches:
      - "main"
      - "develop"


  pull_request:
    branches:
      - "main"

jobs:
  gitleaks:
    name: Gitleaks 
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gastonbarbaccia/gitleaks@v2.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

  saludo:
    name: saludo
    runs-on: ubuntu-latest
    needs: [gitleaks]
    steps:
      - name: saludo command
        run: echo "HolaMundo"